import { netflixLogo } from "../assets/images";

export const STEP_1 = "Step 1";
export const STEP_2 = "Step 2";

export const NEXT = "Next";
export const SAVE = "Save";
export const CANCEL = "Cancel";

// Reference Posts
export const posts = [
  {
    createdAt: "2023-11-23T21:00:48.285Z",
    jobtitle: "UX UI Designer",
    location: "Chennai, Tamilnadu, India (In-office)",
    remotetype: "Part-Time (9.00 am - 5.00 pm IST)",
    salarymax: "60000",
    salarymin: "30000",
    totalemployee: "200",
    industry: "IT",
    experiencemin: "1",
    experiencemax: "2",
    companyname: "Great Vibes - Information Technology",
    applytype: "quickapply",
    id: "1",
  },
  {
    createdAt: "2023-11-23T21:00:48.285Z",
    jobtitle: "Developer",
    location: "Chennai, Tamilnadu, India (In-office)",
    remotetype: "Part-Time (9.00 am - 5.00 pm IST)",
    salarymax: "60000",
    salarymin: "30000",
    totalemployee: "200",
    industry: "IT",
    experiencemin: "1",
    experiencemax: "2",
    companyname: "Great Vibes - Information Technology",
    applytype: "externalapply",
    id: "2",
  },
  {
    createdAt: "2023-11-23T21:00:48.285Z",
    jobtitle: "Interaction Designer",
    location: "Chennai, Tamilnadu, India (In-office)",
    remotetype: "Part-Time (9.00 am - 5.00 pm IST)",
    salarymax: "50000",
    salarymin: "30000",
    totalemployee: "600",
    industry: "IT",
    experiencemin: "1",
    experiencemax: "2",
    companyname: "Great Vibes - Information Technology",
    applytype: "quickapply",
    id: "3",
  },
  {
    createdAt: "2023-11-23T21:00:48.285Z",
    jobtitle: "SEO Analyst",
    location: "Chennai, Tamilnadu, India (In-office)",
    remotetype: "Part-Time (9.00 am - 5.00 pm IST)",
    salarymax: "60000",
    salarymin: "30000",
    totalemployee: "200",
    industry: "IT",
    experiencemin: "1",
    experiencemax: "2",
    companyname: "Great Vibes - Information Technology",
    applytype: "quickapply",
    id: "4",
  },
];

export const formFields = [
  {
    id: "f1",
    label: "Job title",
    name: "jobtitle",
    type: "text",
    placeholder: "ex. UX UI Designer",
    isRequired: true,
    step: "Step 1",
    multiCol: false,
    showLabel: true,
  },
  {
    id: "f2",
    label: "Company name",
    name: "companyname",
    type: "text",
    placeholder: "ex. Google",
    isRequired: true,
    step: "Step 1",
    multiCol: false,
    showLabel: true,
  },
  {
    id: "f3",
    label: "Industry",
    name: "industry",
    type: "text",
    placeholder: "ex. Information Technology",
    isRequired: true,
    step: "Step 1",
    multiCol: false,
    showLabel: true,
  },
  {
    id: "f4",
    label: "Location",
    name: "location",
    type: "text",
    placeholder: "ex. Chennai",
    isRequired: false,
    step: "Step 1",
    multiCol: true,
    showLabel: true,
  },
  {
    id: "f5",
    label: "Remote type",
    name: "remotetype",
    type: "text",
    placeholder: "ex. In-office",
    isRequired: false,
    step: "Step 1",
    multiCol: true,
    showLabel: true,
  },
  {
    id: "f6",
    label: "Experience",
    name: "experiencemin",
    type: "number",
    placeholder: "Minimum",
    isRequired: false,
    step: "Step 2",
    multiCol: true,
    showLabel: true,
  },
  {
    id: "f7",
    label: "Experience",
    name: "experiencemax",
    type: "number",
    placeholder: "Maximum",
    isRequired: false,
    step: "Step 2",
    multiCol: true,
    showLabel: false,
  },
  {
    id: "f8",
    label: "Salary",
    name: "salarymin",
    type: "number",
    placeholder: "Minimum",
    isRequired: false,
    step: "Step 2",
    multiCol: true,
    showLabel: true,
  },
  {
    id: "f9",
    label: "Salary",
    name: "salarymax",
    type: "number",
    placeholder: "Maximum",
    isRequired: false,
    step: "Step 2",
    multiCol: true,
    showLabel: false,
  },
  {
    id: "f10",
    label: "Total employee",
    name: "totalemployee",
    type: "number",
    placeholder: "ex. 100",
    isRequired: false,
    step: "Step 2",
    multiCol: false,
    showLabel: true,
  },
  {
    id: "f11",
    label: "Apply type",
    type: "radio",
    step: "Step 2",
    showLabel: true,
    items: [
      {
        id: "f111",
        label: "Quick apply",
        value: "quickapply",
        name: "applytype",
      },
      {
        id: "f112",
        label: "External apply",
        value: "externalapply",
        name: "applytype",
      },
    ],
  },
];
